#!/bin/bash
set -e

export SBT_OPTS="${SBT_OPTS} -Dsbt.io.jdktimestamps=true"

cat .io.livecode.ch/header.txt $2 .io.livecode.ch/mid.txt $1 .io.livecode.ch/footer.txt >src/test/scala/lms/tutorial/out.scala

sbt -no-colors "testOnly *OutTest*"
cat src/out/out.actual.scala
