#!/bin/bash
set -e

export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
export PATH=$JAVA_HOME/bin:$PATH
export SBT_OPTS="${SBT_OPTS} -Dsbt.io.jdktimestamps=true"

cat .io.livecode.ch/header.txt $2 .io.livecode.ch/mid.txt $1 .io.livecode.ch/footer.txt >src/test/scala/lms/tutorial/out.scala

sbt -no-colors "testOnly *OutTest*"
echo "<code>"
cat src/out/out.actual.scala
echo "</code>"
